#!/bin/sh
# Asterisk entrypoint — auto-detects host IP and container subnet for NAT/RTP config.
# Generates /etc/asterisk/pjsip_transport.conf before starting Asterisk.

set -e

# Use EXTERNAL_IP if provided, otherwise detect.
NAT_IP="${EXTERNAL_IP:-}"

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(getent ahostsv4 host.docker.internal 2>/dev/null | head -1 | awk '{print $1}')
fi

if [ -z "$NAT_IP" ]; then
  NAT_IP=$(ip route 2>/dev/null | grep default | awk '{print $3}')
fi

if [ -z "$NAT_IP" ]; then
  echo "WARNING: Could not detect host IP. SIP NAT/RTP may not work."
  NAT_IP="0.0.0.0"
fi

# Detect container's own IP for local_net. Use /32 (not /24) because
# the Docker gateway (e.g. 10.200.1.1) also lives on the /24 subnet,
# and Docker Desktop proxies host traffic through the gateway IP.
# With /24, Asterisk would treat host traffic as "local" and skip
# external_media_address. With /32, only the container itself is "local".
CONTAINER_IP=$(hostname -i 2>/dev/null | awk '{print $1}')
if [ -z "$CONTAINER_IP" ]; then
  CONTAINER_IP="127.0.0.1"
fi

echo "xphone-test Asterisk: NAT_IP=$NAT_IP CONTAINER_IP=$CONTAINER_IP"

cat > /etc/asterisk/pjsip_transport.conf << EOF
; Auto-generated by entrypoint.sh
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=$NAT_IP
external_signaling_address=$NAT_IP
local_net=$CONTAINER_IP/32
local_net=127.0.0.0/8
EOF

exec /usr/sbin/asterisk "$@"
