[modules]
autoload=yes

; Core PJSIP
load => res_pjsip.so
load => res_pjsip_session.so
load => res_pjsip_registrar.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_user.so
load => res_pjsip_caller_id.so
load => res_pjsip_logger.so
load => res_pjsip_refer.so
load => res_pjsip_rfc3326.so

; Channel driver
load => chan_pjsip.so

; Applications
load => app_dial.so
load => app_noop.so
load => app_hangup.so
load => app_verbose.so
load => app_set.so
load => app_echo.so
load => app_playback.so

; Messaging (SIP MESSAGE relay)
load => res_pjsip_messaging.so

; PBX
load => pbx_config.so

; Core
load => res_timing_timerfd.so
load => res_rtp_asterisk.so

; Don't load unnecessary modules
noload => chan_dahdi.so
noload => chan_iax2.so
noload => chan_sip.so
noload => res_pjsip_transport_websocket.so
noload => res_timing_pthread.so
noload => res_config_sqlite3.so
noload => pbx_realtime.so
noload => res_realtime.so
noload => res_ari.so
noload => res_http_websocket.so
noload => res_stasis.so
